import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'localadmin' at '7/13/17 9:49 AM' with Gradle 2.9
 *
 * @author localadmin, @date 7/13/17 9:49 AM
 */
public class Library {
    public  static List<Integer> removeEven(List<Integer> numbers) {
        if(null == numbers) {
            throw new IllegalArgumentException("");
        }
        return numbers
                .stream()
                .filter((Integer theNumber)-> theNumber %2 != 0)
                .collect(Collectors.toList());
    }

    public static List<String> removeSwiftFox(List<String> foxes) {
        if (null == foxes) {
            throw new IllegalArgumentException("");
        }
        return foxes
                .stream()
                .filter((String theFoxes)-> theFoxes != "Swift Fox")
                .collect(Collectors.toList());
    }


    public static List<Person> findAdult(List<Person> personList) {
        if( null == personList)
            throw new IllegalArgumentException();
        return personList;
    }
}
